package firezone_test

import (
	"context"
	"net/http"
	"testing"

	firezone "github.com/firezone/firezone-go"
	"github.com/firezone/firezone-go/internal/testutil"
)

func TestGatewaysService_Provision(t *testing.T) {
	var gotMethod, gotPath string
	var gotBody map[string]any
	client := testutil.NewClient(t, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath = r.Method, r.URL.Path
		decodeJSONBody(t, r, &gotBody)
		testutil.JSONResponse(http.StatusCreated, map[string]any{
			"data": map[string]any{
				"id": "gw-1", "name": "gw-nyc-1", "ipv4": "", "ipv6": "", "online": false,
				"token": "one-time-secret",
			},
		})(w, r)
	}))

	provisioned, err := client.Sites.Gateways("site-1").Provision(context.Background(), &firezone.ProvisionGatewayRequest{Name: "gw-nyc-1"})
	if err != nil {
		t.Fatalf("Provision returned error: %v", err)
	}

	if gotMethod != http.MethodPost || gotPath != "/sites/site-1/gateways" {
		t.Errorf("request = %s %s, want POST /sites/site-1/gateways", gotMethod, gotPath)
	}
	reqGateway, ok := gotBody["gateway"].(map[string]any)
	if !ok || reqGateway["name"] != "gw-nyc-1" {
		t.Errorf("body[gateway] = %v, want {name: gw-nyc-1}", gotBody["gateway"])
	}

	if provisioned.ID != "gw-1" || provisioned.Name != "gw-nyc-1" {
		t.Errorf("provisioned = %+v, want ID=gw-1 Name=gw-nyc-1", provisioned)
	}
	if provisioned.Online {
		t.Error("provisioned.Online = true, want false (never connected)")
	}
	if provisioned.Token != "one-time-secret" {
		t.Errorf("provisioned.Token = %q, want one-time-secret", provisioned.Token)
	}
}

func TestGatewaysService_Provision_AutoGeneratedName(t *testing.T) {
	var gotBody map[string]any
	client := testutil.NewClient(t, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		decodeJSONBody(t, r, &gotBody)
		testutil.JSONResponse(http.StatusCreated, map[string]any{
			"data": map[string]any{"id": "gw-1", "name": "random-name", "online": false, "token": "secret"},
		})(w, r)
	}))

	// Passing nil Name (empty request) matches the API's own default:
	// a random name is generated when omitted.
	provisioned, err := client.Sites.Gateways("site-1").Provision(context.Background(), &firezone.ProvisionGatewayRequest{})
	if err != nil {
		t.Fatalf("Provision returned error: %v", err)
	}
	if _, hasName := gotBody["gateway"].(map[string]any)["name"]; hasName {
		t.Error("body.gateway.name was sent even though empty, want omitted")
	}
	if provisioned.Name != "random-name" {
		t.Errorf("provisioned.Name = %q, want random-name", provisioned.Name)
	}
}

func TestGatewaysService_Get_NoTokenField(t *testing.T) {
	// Get returns *Gateway, which has no Token field at all - the type
	// system itself prevents a caller from expecting a token after a
	// refresh. This test just documents/locks in that Get's return type
	// is Gateway, not ProvisionedGateway.
	client := testutil.NewClient(t, testutil.JSONResponse(http.StatusOK, map[string]any{
		"data": map[string]any{"id": "gw-1", "name": "gw-nyc-1", "online": true},
	}))

	gateway, err := client.Sites.Gateways("site-1").Get(context.Background(), "gw-1")
	if err != nil {
		t.Fatalf("Get returned error: %v", err)
	}
	if gateway.ID != "gw-1" || !gateway.Online {
		t.Errorf("gateway = %+v, want ID=gw-1 Online=true", gateway)
	}
}

func TestGatewaysService_Update_Rename(t *testing.T) {
	var gotMethod, gotPath string
	client := testutil.NewClient(t, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod, gotPath = r.Method, r.URL.Path
		testutil.JSONResponse(http.StatusOK, map[string]any{
			"data": map[string]any{"id": "gw-1", "name": "renamed", "online": false},
		})(w, r)
	}))

	gateway, err := client.Sites.Gateways("site-1").Update(context.Background(), "gw-1", &firezone.UpdateGatewayRequest{Name: "renamed"})
	if err != nil {
		t.Fatalf("Update returned error: %v", err)
	}
	if gotMethod != http.MethodPut || gotPath != "/sites/site-1/gateways/gw-1" {
		t.Errorf("request = %s %s, want PUT /sites/site-1/gateways/gw-1", gotMethod, gotPath)
	}
	if gateway.Name != "renamed" {
		t.Errorf("gateway.Name = %q, want renamed", gateway.Name)
	}
}

func TestGatewaysService_List_Filters(t *testing.T) {
	tests := []struct {
		name      string
		opts      *firezone.GatewayListOptions
		wantQuery string
	}{
		{name: "by name", opts: &firezone.GatewayListOptions{Name: "gw-us-east-1"}, wantQuery: "name=gw-us-east-1"},
		{name: "by ipv4", opts: &firezone.GatewayListOptions{IPv4: "100.64.0.1"}, wantQuery: "ipv4=100.64.0.1"},
		{name: "by ipv6", opts: &firezone.GatewayListOptions{IPv6: "fd00::1"}, wantQuery: "ipv6=fd00%3A%3A1"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var gotQuery string
			client := testutil.NewClient(t, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				gotQuery = r.URL.RawQuery
				testutil.JSONResponse(http.StatusOK, map[string]any{
					"data":     []map[string]any{},
					"metadata": map[string]any{"count": 0, "limit": 50, "next_page": "", "prev_page": ""},
				})(w, r)
			}))

			_, err := client.Sites.Gateways("site-1").List(context.Background(), tt.opts)
			if err != nil {
				t.Fatalf("List returned error: %v", err)
			}
			if gotQuery != tt.wantQuery {
				t.Errorf("query = %q, want %q", gotQuery, tt.wantQuery)
			}
		})
	}
}
